### ISSUE TITLE
MS-COCO 2014 or 2017

### ISSUE THREAD

**Issue by karenyun** [s-gupta/v-coco#3]
Hi, @s-gupta, I have a question about the MS-COCO version, since there are two versions for it, I need to download the MS-COCO 2014 or 2017?

And where to download the file 'instances_vcoco_all_2014.json''? 
Thanks!!

**Comment by FesianXu** [comment]
It should be MS-COCO 2014 and the `instances_vcoco_all_2014.json` is generated by the script in the codebase and you don't need to download it.

**Comment by karenyun** [comment]
okay, many thanks!

**Comment by mulualem1184** [comment]
instances_vcoco_all_2014.json not created by codebase in vcoco but it gives an error of  "No such file or directory: '/content/drive/My Drive/Colab Notebooks/data/instances_vcoco_all_2014.json'"
